#! /bin/bash
rm --recursive --force ./Documentation/Reference/*
pdoc3 --html --output-dir ./Documentation/Reference ./Experimentalist
cp -a ./Documentation/Reference/Experimentalist/. ./Documentation/Reference
